language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

env:
  global:
    - secure: "BQMtAdWgePYWXO02eUVFW2I16+hovPdMgOk9ff0cUNighzVTUK3EnVDSGGi4dSSooBav6cIAR0NsKUE61H00R8MsGroSaGtRZpak8KB/O+X3fYuh7h1A03zvV7ebwJR7DqNSmDeFAmmOwBuJIaaZr7yG3KEHYGBtPHrWnDS/8MI="
    - secure: "aVBVmwNRY6v1Pg4faoeHWI8GgufkzM0AH+HKTRLWyuC/VsvHpFAbtrQ80Y4HXoCm7Wz7PaihQkMEXBV6GAfsv99YwNu9X6JwNb2ccnEKb97eO/gObeK0nM0IaVDHPznRkyUnKPegVOTe53ch2VSUlCfteyHVOnPZ5fSH9Oxej0c="

after_success:
  - mvn clean deploy --settings settings.xml