language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

env:
  global:
    - secure: "BQMtAdWgePYWXO02eUVFW2I16+hovPdMgOk9ff0cUNighzVTUK3EnVDSGGi4dSSooBav6cIAR0NsKUE61H00R8MsGroSaGtRZpak8KB/O+X3fYuh7h1A03zvV7ebwJR7DqNSmDeFAmmOwBuJIaaZr7yG3KEHYGBtPHrWnDS/8MI="
    - secure: "aVBVmwNRY6v1Pg4faoeHWI8GgufkzM0AH+HKTRLWyuC/VsvHpFAbtrQ80Y4HXoCm7Wz7PaihQkMEXBV6GAfsv99YwNu9X6JwNb2ccnEKb97eO/gObeK0nM0IaVDHPznRkyUnKPegVOTe53ch2VSUlCfteyHVOnPZ5fSH9Oxej0c="
    - secure: "NxGKi/aTlrr1KWqrLU3OW6SDOSpmNyoPadGbxivz7qf8G4aYoBHmaaTXm3BaT2jnT+PxcD8trE5A8+H2OOAKBTZHTevuwOxfuyj4T7g1lRq029opr8UD2l2QKftUOjs/2fhV+/rfFxC2ZvN56HSwId8+EHxvkIJv54KctDCyU/U="

script: mvn test jacoco:report coveralls:jacoco

after_success:
  - mvn deploy --settings settings.xml
